<?php
/**
 * NotificationOptionsModel
 *
 * PHP version 5
 *
 * @category Class
 * @package  BumbalClient
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bumbal Client Api
 *
 * Bumbal API documentation
 *
 * OpenAPI spec version: 2.0
 * Contact: gerb@bumbal.eu
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace BumbalClient\Model;

use \ArrayAccess;

/**
 * NotificationOptionsModel Class Doc Comment
 *
 * @category    Class
 * @package     BumbalClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class NotificationOptionsModel implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'NotificationOptionsModel';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'include_notification_files' => 'bool',
        'include_updated_by' => 'bool',
        'include_record_info' => 'bool',
        'include_object_type_name' => 'bool',
        'include_notification_category_name' => 'bool',
        'include_user_notification' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerFormats = [
        'include_notification_files' => null,
        'include_updated_by' => null,
        'include_record_info' => null,
        'include_object_type_name' => null,
        'include_notification_category_name' => null,
        'include_user_notification' => null
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'include_notification_files' => 'include_notification_files',
        'include_updated_by' => 'include_updated_by',
        'include_record_info' => 'include_record_info',
        'include_object_type_name' => 'include_object_type_name',
        'include_notification_category_name' => 'include_notification_category_name',
        'include_user_notification' => 'include_user_notification'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'include_notification_files' => 'setIncludeNotificationFiles',
        'include_updated_by' => 'setIncludeUpdatedBy',
        'include_record_info' => 'setIncludeRecordInfo',
        'include_object_type_name' => 'setIncludeObjectTypeName',
        'include_notification_category_name' => 'setIncludeNotificationCategoryName',
        'include_user_notification' => 'setIncludeUserNotification'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'include_notification_files' => 'getIncludeNotificationFiles',
        'include_updated_by' => 'getIncludeUpdatedBy',
        'include_record_info' => 'getIncludeRecordInfo',
        'include_object_type_name' => 'getIncludeObjectTypeName',
        'include_notification_category_name' => 'getIncludeNotificationCategoryName',
        'include_user_notification' => 'getIncludeUserNotification'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['include_notification_files'] = isset($data['include_notification_files']) ? $data['include_notification_files'] : null;
        $this->container['include_updated_by'] = isset($data['include_updated_by']) ? $data['include_updated_by'] : null;
        $this->container['include_record_info'] = isset($data['include_record_info']) ? $data['include_record_info'] : null;
        $this->container['include_object_type_name'] = isset($data['include_object_type_name']) ? $data['include_object_type_name'] : null;
        $this->container['include_notification_category_name'] = isset($data['include_notification_category_name']) ? $data['include_notification_category_name'] : null;
        $this->container['include_user_notification'] = isset($data['include_user_notification']) ? $data['include_user_notification'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        return true;
    }


    /**
     * Gets include_notification_files
     * @return bool
     */
    public function getIncludeNotificationFiles()
    {
        return $this->container['include_notification_files'];
    }

    /**
     * Sets include_notification_files
     * @param bool $include_notification_files 
     * @return $this
     */
    public function setIncludeNotificationFiles($include_notification_files)
    {
        $this->container['include_notification_files'] = $include_notification_files;

        return $this;
    }

    /**
     * Gets include_updated_by
     * @return bool
     */
    public function getIncludeUpdatedBy()
    {
        return $this->container['include_updated_by'];
    }

    /**
     * Sets include_updated_by
     * @param bool $include_updated_by 
     * @return $this
     */
    public function setIncludeUpdatedBy($include_updated_by)
    {
        $this->container['include_updated_by'] = $include_updated_by;

        return $this;
    }

    /**
     * Gets include_record_info
     * @return bool
     */
    public function getIncludeRecordInfo()
    {
        return $this->container['include_record_info'];
    }

    /**
     * Sets include_record_info
     * @param bool $include_record_info 
     * @return $this
     */
    public function setIncludeRecordInfo($include_record_info)
    {
        $this->container['include_record_info'] = $include_record_info;

        return $this;
    }

    /**
     * Gets include_object_type_name
     * @return bool
     */
    public function getIncludeObjectTypeName()
    {
        return $this->container['include_object_type_name'];
    }

    /**
     * Sets include_object_type_name
     * @param bool $include_object_type_name 
     * @return $this
     */
    public function setIncludeObjectTypeName($include_object_type_name)
    {
        $this->container['include_object_type_name'] = $include_object_type_name;

        return $this;
    }

    /**
     * Gets include_notification_category_name
     * @return bool
     */
    public function getIncludeNotificationCategoryName()
    {
        return $this->container['include_notification_category_name'];
    }

    /**
     * Sets include_notification_category_name
     * @param bool $include_notification_category_name 
     * @return $this
     */
    public function setIncludeNotificationCategoryName($include_notification_category_name)
    {
        $this->container['include_notification_category_name'] = $include_notification_category_name;

        return $this;
    }

    /**
     * Gets include_user_notification
     * @return bool
     */
    public function getIncludeUserNotification()
    {
        return $this->container['include_user_notification'];
    }

    /**
     * Sets include_user_notification
     * @param bool $include_user_notification 
     * @return $this
     */
    public function setIncludeUserNotification($include_user_notification)
    {
        $this->container['include_user_notification'] = $include_user_notification;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\BumbalClient\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\BumbalClient\ObjectSerializer::sanitizeForSerialization($this));
    }
}


