<?php
/**
 * AddressModelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  BumbalClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bumbal Client Api
 *
 * Bumbal API documentation
 *
 * OpenAPI spec version: 2.0
 * Contact: gerb@bumbal.eu
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace BumbalClient;

/**
 * AddressModelTest Class Doc Comment
 *
 * @category    Class */
// * @description AddressModel
/**
 * @package     BumbalClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AddressModelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AddressModel"
     */
    public function testAddressModel()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "address_id"
     */
    public function testPropertyAddressId()
    {
    }

    /**
     * Test attribute "party_id"
     */
    public function testPropertyPartyId()
    {
    }

    /**
     * Test attribute "party_name"
     */
    public function testPropertyPartyName()
    {
    }

    /**
     * Test attribute "code"
     */
    public function testPropertyCode()
    {
    }

    /**
     * Test attribute "summary"
     */
    public function testPropertySummary()
    {
    }

    /**
     * Test attribute "full_name"
     */
    public function testPropertyFullName()
    {
    }

    /**
     * Test attribute "name_1"
     */
    public function testPropertyName1()
    {
    }

    /**
     * Test attribute "name_2"
     */
    public function testPropertyName2()
    {
    }

    /**
     * Test attribute "street_1"
     */
    public function testPropertyStreet1()
    {
    }

    /**
     * Test attribute "street_2"
     */
    public function testPropertyStreet2()
    {
    }

    /**
     * Test attribute "full_addressline"
     */
    public function testPropertyFullAddressline()
    {
    }

    /**
     * Test attribute "house_nr"
     */
    public function testPropertyHouseNr()
    {
    }

    /**
     * Test attribute "house_nr_addendum"
     */
    public function testPropertyHouseNrAddendum()
    {
    }

    /**
     * Test attribute "zipcode"
     */
    public function testPropertyZipcode()
    {
    }

    /**
     * Test attribute "city"
     */
    public function testPropertyCity()
    {
    }

    /**
     * Test attribute "state"
     */
    public function testPropertyState()
    {
    }

    /**
     * Test attribute "iso_country"
     */
    public function testPropertyIsoCountry()
    {
    }

    /**
     * Test attribute "country_name"
     */
    public function testPropertyCountryName()
    {
    }

    /**
     * Test attribute "time_from"
     */
    public function testPropertyTimeFrom()
    {
    }

    /**
     * Test attribute "time_to"
     */
    public function testPropertyTimeTo()
    {
    }

    /**
     * Test attribute "duration"
     */
    public function testPropertyDuration()
    {
    }

    /**
     * Test attribute "address_type_names"
     */
    public function testPropertyAddressTypeNames()
    {
    }

    /**
     * Test attribute "emails"
     */
    public function testPropertyEmails()
    {
    }

    /**
     * Test attribute "phone_nrs"
     */
    public function testPropertyPhoneNrs()
    {
    }

    /**
     * Test attribute "latitude"
     */
    public function testPropertyLatitude()
    {
    }

    /**
     * Test attribute "longitude"
     */
    public function testPropertyLongitude()
    {
    }

    /**
     * Test attribute "contact_person"
     */
    public function testPropertyContactPerson()
    {
    }

    /**
     * Test attribute "user_id"
     */
    public function testPropertyUserId()
    {
    }

    /**
     * Test attribute "links"
     */
    public function testPropertyLinks()
    {
    }

    /**
     * Test attribute "meta_data"
     */
    public function testPropertyMetaData()
    {
    }

    /**
     * Test attribute "notes"
     */
    public function testPropertyNotes()
    {
    }

    /**
     * Test attribute "files"
     */
    public function testPropertyFiles()
    {
    }

    /**
     * Test attribute "tag_names"
     */
    public function testPropertyTagNames()
    {
    }

    /**
     * Test attribute "tags"
     */
    public function testPropertyTags()
    {
    }
}
