<?php
/**
 * AutoPlanOptionsModelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  BumbalClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bumbal Client Api
 *
 * Bumbal API documentation
 *
 * OpenAPI spec version: 2.0
 * Contact: gerb@bumbal.eu
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace BumbalClient;

/**
 * AutoPlanOptionsModelTest Class Doc Comment
 *
 * @category    Class */
// * @description AutoPlanOptionsModel
/**
 * @package     BumbalClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AutoPlanOptionsModelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AutoPlanOptionsModel"
     */
    public function testAutoPlanOptionsModel()
    {
    }

    /**
     * Test attribute "synchronous"
     */
    public function testPropertySynchronous()
    {
    }

    /**
     * Test attribute "respond_after_apply_planning"
     */
    public function testPropertyRespondAfterApplyPlanning()
    {
    }

    /**
     * Test attribute "allow_unplanned_activities"
     */
    public function testPropertyAllowUnplannedActivities()
    {
    }

    /**
     * Test attribute "consider_historic_traffic_info"
     */
    public function testPropertyConsiderHistoricTrafficInfo()
    {
    }

    /**
     * Test attribute "in_sequence"
     */
    public function testPropertyInSequence()
    {
    }

    /**
     * Test attribute "do_not_apply_planning"
     */
    public function testPropertyDoNotApplyPlanning()
    {
    }
}
