<?php
/**
 * CarOptionsModelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  BumbalClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bumbal Client Api
 *
 * Bumbal API documentation
 *
 * OpenAPI spec version: 2.0
 * Contact: gerb@bumbal.eu
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace BumbalClient;

/**
 * CarOptionsModelTest Class Doc Comment
 *
 * @category    Class */
// * @description CarOptionsModel
/**
 * @package     BumbalClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CarOptionsModelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CarOptionsModel"
     */
    public function testCarOptionsModel()
    {
    }

    /**
     * Test attribute "include_car_tags"
     */
    public function testPropertyIncludeCarTags()
    {
    }

    /**
     * Test attribute "include_car_meta_data"
     */
    public function testPropertyIncludeCarMetaData()
    {
    }

    /**
     * Test attribute "include_car_links"
     */
    public function testPropertyIncludeCarLinks()
    {
    }

    /**
     * Test attribute "include_updated_by_name"
     */
    public function testPropertyIncludeUpdatedByName()
    {
    }
}
