<?php
/**
 * NotificationOptionsModelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  BumbalClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bumbal Client Api
 *
 * Bumbal API documentation
 *
 * OpenAPI spec version: 2.0
 * Contact: gerb@bumbal.eu
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace BumbalClient;

/**
 * NotificationOptionsModelTest Class Doc Comment
 *
 * @category    Class */
// * @description NotificationOptionsModel
/**
 * @package     BumbalClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class NotificationOptionsModelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "NotificationOptionsModel"
     */
    public function testNotificationOptionsModel()
    {
    }

    /**
     * Test attribute "include_notification_files"
     */
    public function testPropertyIncludeNotificationFiles()
    {
    }

    /**
     * Test attribute "include_updated_by"
     */
    public function testPropertyIncludeUpdatedBy()
    {
    }

    /**
     * Test attribute "include_record_info"
     */
    public function testPropertyIncludeRecordInfo()
    {
    }

    /**
     * Test attribute "include_object_type_name"
     */
    public function testPropertyIncludeObjectTypeName()
    {
    }

    /**
     * Test attribute "include_notification_category_name"
     */
    public function testPropertyIncludeNotificationCategoryName()
    {
    }

    /**
     * Test attribute "include_user_notification"
     */
    public function testPropertyIncludeUserNotification()
    {
    }
}
