<?php
/**
 * PackageLineModelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  BumbalClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bumbal Client Api
 *
 * Bumbal API documentation
 *
 * OpenAPI spec version: 2.0
 * Contact: gerb@bumbal.eu
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace BumbalClient;

/**
 * PackageLineModelTest Class Doc Comment
 *
 * @category    Class */
// * @description PackageLineModel
/**
 * @package     BumbalClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PackageLineModelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PackageLineModel"
     */
    public function testPackageLineModel()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "activity_id"
     */
    public function testPropertyActivityId()
    {
    }

    /**
     * Test attribute "activity_ids"
     */
    public function testPropertyActivityIds()
    {
    }

    /**
     * Test attribute "nr"
     */
    public function testPropertyNr()
    {
    }

    /**
     * Test attribute "status_id"
     */
    public function testPropertyStatusId()
    {
    }

    /**
     * Test attribute "status_name"
     */
    public function testPropertyStatusName()
    {
    }

    /**
     * Test attribute "nr_of_packages"
     */
    public function testPropertyNrOfPackages()
    {
    }

    /**
     * Test attribute "package_type_name"
     */
    public function testPropertyPackageTypeName()
    {
    }

    /**
     * Test attribute "package_type_id"
     */
    public function testPropertyPackageTypeId()
    {
    }

    /**
     * Test attribute "barcode"
     */
    public function testPropertyBarcode()
    {
    }

    /**
     * Test attribute "barcodes"
     */
    public function testPropertyBarcodes()
    {
    }

    /**
     * Test attribute "action_type_id"
     */
    public function testPropertyActionTypeId()
    {
    }

    /**
     * Test attribute "action_type_name"
     */
    public function testPropertyActionTypeName()
    {
    }

    /**
     * Test attribute "checked_by_driver"
     */
    public function testPropertyCheckedByDriver()
    {
    }

    /**
     * Test attribute "adr"
     */
    public function testPropertyAdr()
    {
    }

    /**
     * Test attribute "adr_class"
     */
    public function testPropertyAdrClass()
    {
    }

    /**
     * Test attribute "adr_un_nr"
     */
    public function testPropertyAdrUnNr()
    {
    }

    /**
     * Test attribute "temp"
     */
    public function testPropertyTemp()
    {
    }

    /**
     * Test attribute "temp_min"
     */
    public function testPropertyTempMin()
    {
    }

    /**
     * Test attribute "temp_max"
     */
    public function testPropertyTempMax()
    {
    }

    /**
     * Test attribute "hs_code"
     */
    public function testPropertyHsCode()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "compartments"
     */
    public function testPropertyCompartments()
    {
    }

    /**
     * Test attribute "active"
     */
    public function testPropertyActive()
    {
    }

    /**
     * Test attribute "applied_capacities"
     */
    public function testPropertyAppliedCapacities()
    {
    }

    /**
     * Test attribute "capacities"
     */
    public function testPropertyCapacities()
    {
    }

    /**
     * Test attribute "activity_links"
     */
    public function testPropertyActivityLinks()
    {
    }

    /**
     * Test attribute "links"
     */
    public function testPropertyLinks()
    {
    }

    /**
     * Test attribute "meta_data"
     */
    public function testPropertyMetaData()
    {
    }

    /**
     * Test attribute "notes"
     */
    public function testPropertyNotes()
    {
    }

    /**
     * Test attribute "files"
     */
    public function testPropertyFiles()
    {
    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "updated_at"
     */
    public function testPropertyUpdatedAt()
    {
    }

    /**
     * Test attribute "package_line_created_at"
     */
    public function testPropertyPackageLineCreatedAt()
    {
    }

    /**
     * Test attribute "package_line_updated_at"
     */
    public function testPropertyPackageLineUpdatedAt()
    {
    }

    /**
     * Test attribute "package_line_created_by"
     */
    public function testPropertyPackageLineCreatedBy()
    {
    }

    /**
     * Test attribute "package_line_updated_by"
     */
    public function testPropertyPackageLineUpdatedBy()
    {
    }
}
