<?php
/**
 * QuestionnaireTemplateOptionsModelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  BumbalClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bumbal Client Api
 *
 * Bumbal API documentation
 *
 * OpenAPI spec version: 2.0
 * Contact: gerb@bumbal.eu
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace BumbalClient;

/**
 * QuestionnaireTemplateOptionsModelTest Class Doc Comment
 *
 * @category    Class */
// * @description QuestionnaireTemplateOptionsModel
/**
 * @package     BumbalClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class QuestionnaireTemplateOptionsModelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "QuestionnaireTemplateOptionsModel"
     */
    public function testQuestionnaireTemplateOptionsModel()
    {
    }

    /**
     * Test attribute "include_record_info"
     */
    public function testPropertyIncludeRecordInfo()
    {
    }

    /**
     * Test attribute "include_questions"
     */
    public function testPropertyIncludeQuestions()
    {
    }

    /**
     * Test attribute "include_options"
     */
    public function testPropertyIncludeOptions()
    {
    }

    /**
     * Test attribute "include_texts"
     */
    public function testPropertyIncludeTexts()
    {
    }

    /**
     * Test attribute "include_question_type_name"
     */
    public function testPropertyIncludeQuestionTypeName()
    {
    }

    /**
     * Test attribute "include_zones"
     */
    public function testPropertyIncludeZones()
    {
    }

    /**
     * Test attribute "include_brands"
     */
    public function testPropertyIncludeBrands()
    {
    }

    /**
     * Test attribute "include_tag_ids"
     */
    public function testPropertyIncludeTagIds()
    {
    }

    /**
     * Test attribute "include_tag_names"
     */
    public function testPropertyIncludeTagNames()
    {
    }

    /**
     * Test attribute "include_tags"
     */
    public function testPropertyIncludeTags()
    {
    }

    /**
     * Test attribute "include_zone_ids"
     */
    public function testPropertyIncludeZoneIds()
    {
    }

    /**
     * Test attribute "include_zone_names"
     */
    public function testPropertyIncludeZoneNames()
    {
    }

    /**
     * Test attribute "include_brand_ids"
     */
    public function testPropertyIncludeBrandIds()
    {
    }

    /**
     * Test attribute "include_brand_names"
     */
    public function testPropertyIncludeBrandNames()
    {
    }
}
