<?php
/**
 * QuestionnaireModelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  BumbalClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bumbal Client Api
 *
 * Bumbal API documentation
 *
 * OpenAPI spec version: 2.0
 * Contact: gerb@bumbal.eu
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace BumbalClient;

/**
 * QuestionnaireModelTest Class Doc Comment
 *
 * @category    Class */
// * @description QuestionnaireModel
/**
 * @package     BumbalClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class QuestionnaireModelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "QuestionnaireModel"
     */
    public function testQuestionnaireModel()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "active"
     */
    public function testPropertyActive()
    {
    }

    /**
     * Test attribute "questionnaire_template_id"
     */
    public function testPropertyQuestionnaireTemplateId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "questionnaire_type_id"
     */
    public function testPropertyQuestionnaireTypeId()
    {
    }

    /**
     * Test attribute "questionnaire_type_name"
     */
    public function testPropertyQuestionnaireTypeName()
    {
    }

    /**
     * Test attribute "lang_code"
     */
    public function testPropertyLangCode()
    {
    }

    /**
     * Test attribute "answers"
     */
    public function testPropertyAnswers()
    {
    }

    /**
     * Test attribute "object_type"
     */
    public function testPropertyObjectType()
    {
    }

    /**
     * Test attribute "object_type_name"
     */
    public function testPropertyObjectTypeName()
    {
    }

    /**
     * Test attribute "object_id"
     */
    public function testPropertyObjectId()
    {
    }
}
