<?php
/**
 * RouteFiltersModelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  BumbalClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bumbal Client Api
 *
 * Bumbal API documentation
 *
 * OpenAPI spec version: 2.0
 * Contact: gerb@bumbal.eu
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace BumbalClient;

/**
 * RouteFiltersModelTest Class Doc Comment
 *
 * @category    Class */
// * @description RouteFiltersModel
/**
 * @package     BumbalClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RouteFiltersModelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "RouteFiltersModel"
     */
    public function testRouteFiltersModel()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "nr"
     */
    public function testPropertyNr()
    {
    }

    /**
     * Test attribute "date_time_from"
     */
    public function testPropertyDateTimeFrom()
    {
    }

    /**
     * Test attribute "date_time_to"
     */
    public function testPropertyDateTimeTo()
    {
    }

    /**
     * Test attribute "earliest_date_time_since"
     */
    public function testPropertyEarliestDateTimeSince()
    {
    }

    /**
     * Test attribute "earliest_date_time_till"
     */
    public function testPropertyEarliestDateTimeTill()
    {
    }

    /**
     * Test attribute "latest_date_time_since"
     */
    public function testPropertyLatestDateTimeSince()
    {
    }

    /**
     * Test attribute "latest_date_time_till"
     */
    public function testPropertyLatestDateTimeTill()
    {
    }

    /**
     * Test attribute "updated_at"
     */
    public function testPropertyUpdatedAt()
    {
    }

    /**
     * Test attribute "updated_at_since"
     */
    public function testPropertyUpdatedAtSince()
    {
    }

    /**
     * Test attribute "updated_at_till"
     */
    public function testPropertyUpdatedAtTill()
    {
    }

    /**
     * Test attribute "status_id"
     */
    public function testPropertyStatusId()
    {
    }

    /**
     * Test attribute "driver_id"
     */
    public function testPropertyDriverId()
    {
    }

    /**
     * Test attribute "recurrence_id"
     */
    public function testPropertyRecurrenceId()
    {
    }

    /**
     * Test attribute "tag_names"
     */
    public function testPropertyTagNames()
    {
    }

    /**
     * Test attribute "zone_names"
     */
    public function testPropertyZoneNames()
    {
    }

    /**
     * Test attribute "optimized"
     */
    public function testPropertyOptimized()
    {
    }

    /**
     * Test attribute "blocked"
     */
    public function testPropertyBlocked()
    {
    }
}
