<?php
/**
 * SayWhenVisitModelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  BumbalClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bumbal Client Api
 *
 * Bumbal API documentation
 *
 * OpenAPI spec version: 2.0
 * Contact: gerb@bumbal.eu
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace BumbalClient;

/**
 * SayWhenVisitModelTest Class Doc Comment
 *
 * @category    Class */
// * @description SayWhenVisitModel
/**
 * @package     BumbalClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SayWhenVisitModelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SayWhenVisitModel"
     */
    public function testSayWhenVisitModel()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "current_state"
     */
    public function testPropertyCurrentState()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "offered_by_owner"
     */
    public function testPropertyOfferedByOwner()
    {
    }

    /**
     * Test attribute "preferences_received"
     */
    public function testPropertyPreferencesReceived()
    {
    }

    /**
     * Test attribute "planned_by_partner"
     */
    public function testPropertyPlannedByPartner()
    {
    }

    /**
     * Test attribute "completed_by_partner"
     */
    public function testPropertyCompletedByPartner()
    {
    }
}
