<?php
/**
 * SettingsOptionsModelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  BumbalClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bumbal Client Api
 *
 * Bumbal API documentation
 *
 * OpenAPI spec version: 2.0
 * Contact: gerb@bumbal.eu
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace BumbalClient;

/**
 * SettingsOptionsModelTest Class Doc Comment
 *
 * @category    Class */
// * @description SettingsOptionsModel
/**
 * @package     BumbalClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SettingsOptionsModelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "SettingsOptionsModel"
     */
    public function testSettingsOptionsModel()
    {
    }

    /**
     * Test attribute "include_settings_group_name"
     */
    public function testPropertyIncludeSettingsGroupName()
    {
    }

    /**
     * Test attribute "include_record_info"
     */
    public function testPropertyIncludeRecordInfo()
    {
    }

    /**
     * Test attribute "include_record_object"
     */
    public function testPropertyIncludeRecordObject()
    {
    }
}
