<?php
/**
 * UserNotificationModelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  BumbalClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bumbal Client Api
 *
 * Bumbal API documentation
 *
 * OpenAPI spec version: 2.0
 * Contact: gerb@bumbal.eu
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace BumbalClient;

/**
 * UserNotificationModelTest Class Doc Comment
 *
 * @category    Class */
// * @description UserNotificationModel
/**
 * @package     BumbalClient
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class UserNotificationModelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "UserNotificationModel"
     */
    public function testUserNotificationModel()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "user_id"
     */
    public function testPropertyUserId()
    {
    }

    /**
     * Test attribute "notification_id"
     */
    public function testPropertyNotificationId()
    {
    }

    /**
     * Test attribute "unread"
     */
    public function testPropertyUnread()
    {
    }

    /**
     * Test attribute "pinned"
     */
    public function testPropertyPinned()
    {
    }

    /**
     * Test attribute "archived"
     */
    public function testPropertyArchived()
    {
    }

    /**
     * Test attribute "archive_date"
     */
    public function testPropertyArchiveDate()
    {
    }

    /**
     * Test attribute "notification_created_at"
     */
    public function testPropertyNotificationCreatedAt()
    {
    }

    /**
     * Test attribute "object_id"
     */
    public function testPropertyObjectId()
    {
    }

    /**
     * Test attribute "object_type"
     */
    public function testPropertyObjectType()
    {
    }

    /**
     * Test attribute "notification_updated_at"
     */
    public function testPropertyNotificationUpdatedAt()
    {
    }

    /**
     * Test attribute "object_type_name"
     */
    public function testPropertyObjectTypeName()
    {
    }
}
