<?php
/**
 * AddressApiTest
 * PHP version 5
 *
 * @category Class
 * @package  BumbalClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bumbal Client Api
 *
 * Bumbal API documentation
 *
 * OpenAPI spec version: 2.0
 * Contact: gerb@bumbal.eu
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace BumbalClient;

use \BumbalClient\Configuration;
use \BumbalClient\ApiClient;
use \BumbalClient\ApiException;
use \BumbalClient\ObjectSerializer;

/**
 * AddressApiTest Class Doc Comment
 *
 * @category Class
 * @package  BumbalClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AddressApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for deleteAddress
     *
     * Delete an address.
     *
     */
    public function testDeleteAddress()
    {
    }

    /**
     * Test case for retrieveAddress
     *
     * Retrieve a Address.
     *
     */
    public function testRetrieveAddress()
    {
    }

    /**
     * Test case for retrieveListAddress
     *
     * Retrieve List of Addresses.
     *
     */
    public function testRetrieveListAddress()
    {
    }

    /**
     * Test case for reverseGeoCodeAddress
     *
     * Reverse Geo Code a address.
     *
     */
    public function testReverseGeoCodeAddress()
    {
    }

    /**
     * Test case for setAddress
     *
     * Add a new Address.
     *
     */
    public function testSetAddress()
    {
    }

    /**
     * Test case for updateAddress
     *
     * Update a address.
     *
     */
    public function testUpdateAddress()
    {
    }
}
