<?php
/**
 * AssignmentApiTest
 * PHP version 5
 *
 * @category Class
 * @package  BumbalClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bumbal Client Api
 *
 * Bumbal API documentation
 *
 * OpenAPI spec version: 2.0
 * Contact: gerb@bumbal.eu
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace BumbalClient;

use \BumbalClient\Configuration;
use \BumbalClient\ApiClient;
use \BumbalClient\ApiException;
use \BumbalClient\ObjectSerializer;

/**
 * AssignmentApiTest Class Doc Comment
 *
 * @category Class
 * @package  BumbalClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AssignmentApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for deleteAssignment
     *
     * Delete an assignment.
     *
     */
    public function testDeleteAssignment()
    {
    }

    /**
     * Test case for retrieveAssignment
     *
     * Find assignment by ID.
     *
     */
    public function testRetrieveAssignment()
    {
    }

    /**
     * Test case for retrieveListAssignment
     *
     * Retrieve List of Assignments.
     *
     */
    public function testRetrieveListAssignment()
    {
    }

    /**
     * Test case for setAssignment
     *
     * Set (create or update) an Assignment.
     *
     */
    public function testSetAssignment()
    {
    }

    /**
     * Test case for updateAssignment
     *
     * Update a assignment.
     *
     */
    public function testUpdateAssignment()
    {
    }
}
