<?php
/**
 * BrandApiTest
 * PHP version 5
 *
 * @category Class
 * @package  BumbalClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bumbal Client Api
 *
 * Bumbal API documentation
 *
 * OpenAPI spec version: 2.0
 * Contact: gerb@bumbal.eu
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace BumbalClient;

use \BumbalClient\Configuration;
use \BumbalClient\ApiClient;
use \BumbalClient\ApiException;
use \BumbalClient\ObjectSerializer;

/**
 * BrandApiTest Class Doc Comment
 *
 * @category Class
 * @package  BumbalClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class BrandApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createBrand
     *
     * Add a new Brand.
     *
     */
    public function testCreateBrand()
    {
    }

    /**
     * Test case for deleteBrand
     *
     * Delete a Brand.
     *
     */
    public function testDeleteBrand()
    {
    }

    /**
     * Test case for retrieveBrand
     *
     * Retrieve a Brand.
     *
     */
    public function testRetrieveBrand()
    {
    }

    /**
     * Test case for retrieveListBrand
     *
     * Retrieve List of Brands.
     *
     */
    public function testRetrieveListBrand()
    {
    }

    /**
     * Test case for setBrand
     *
     * Set (create or update) a Brand.
     *
     */
    public function testSetBrand()
    {
    }

    /**
     * Test case for updateBrand
     *
     * Update a Brand.
     *
     */
    public function testUpdateBrand()
    {
    }
}
