<?php
/**
 * CarApiTest
 * PHP version 5
 *
 * @category Class
 * @package  BumbalClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bumbal Client Api
 *
 * Bumbal API documentation
 *
 * OpenAPI spec version: 2.0
 * Contact: gerb@bumbal.eu
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace BumbalClient;

use \BumbalClient\Configuration;
use \BumbalClient\ApiClient;
use \BumbalClient\ApiException;
use \BumbalClient\ObjectSerializer;

/**
 * CarApiTest Class Doc Comment
 *
 * @category Class
 * @package  BumbalClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CarApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createCar
     *
     * Add a car.
     *
     */
    public function testCreateCar()
    {
    }

    /**
     * Test case for deleteCar
     *
     * Delete an car.
     *
     */
    public function testDeleteCar()
    {
    }

    /**
     * Test case for retrieveCar
     *
     * Find car by ID.
     *
     */
    public function testRetrieveCar()
    {
    }

    /**
     * Test case for retrieveListCar
     *
     * Retrieve List of Cars.
     *
     */
    public function testRetrieveListCar()
    {
    }

    /**
     * Test case for setCar
     *
     * Set (create or update) a car.
     *
     */
    public function testSetCar()
    {
    }

    /**
     * Test case for updateCar
     *
     * Update a car.
     *
     */
    public function testUpdateCar()
    {
    }
}
