<?php
/**
 * DriverunavailabilityApiTest
 * PHP version 5
 *
 * @category Class
 * @package  BumbalClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bumbal Client Api
 *
 * Bumbal API documentation
 *
 * OpenAPI spec version: 2.0
 * Contact: gerb@bumbal.eu
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace BumbalClient;

use \BumbalClient\Configuration;
use \BumbalClient\ApiClient;
use \BumbalClient\ApiException;
use \BumbalClient\ObjectSerializer;

/**
 * DriverunavailabilityApiTest Class Doc Comment
 *
 * @category Class
 * @package  BumbalClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DriverunavailabilityApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createDriverUnavailability
     *
     * Add a new DriverUnavailability.
     *
     */
    public function testCreateDriverUnavailability()
    {
    }

    /**
     * Test case for deleteDriverUnavailability
     *
     * Delete a DriverUnavailability entry.
     *
     */
    public function testDeleteDriverUnavailability()
    {
    }

    /**
     * Test case for retrieveDriverUnavailability
     *
     * Retrieve a DriverUnavailability.
     *
     */
    public function testRetrieveDriverUnavailability()
    {
    }

    /**
     * Test case for retrieveListDriverUnavailability
     *
     * Retrieve List of DriverUnavailability.
     *
     */
    public function testRetrieveListDriverUnavailability()
    {
    }

    /**
     * Test case for setDriverUnavailability
     *
     * Set (create or update) a driver unavailability.
     *
     */
    public function testSetDriverUnavailability()
    {
    }

    /**
     * Test case for updateDriverUnavailability
     *
     * Update a specific DriverUnavailability object.
     *
     */
    public function testUpdateDriverUnavailability()
    {
    }
}
