<?php
/**
 * MetadataApiTest
 * PHP version 5
 *
 * @category Class
 * @package  BumbalClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bumbal Client Api
 *
 * Bumbal API documentation
 *
 * OpenAPI spec version: 2.0
 * Contact: gerb@bumbal.eu
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace BumbalClient;

use \BumbalClient\Configuration;
use \BumbalClient\ApiClient;
use \BumbalClient\ApiException;
use \BumbalClient\ObjectSerializer;

/**
 * MetadataApiTest Class Doc Comment
 *
 * @category Class
 * @package  BumbalClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class MetadataApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createMetaData
     *
     * Add a new MetaData.
     *
     */
    public function testCreateMetaData()
    {
    }

    /**
     * Test case for deleteMetaData
     *
     * Delete a MetaData entry.
     *
     */
    public function testDeleteMetaData()
    {
    }

    /**
     * Test case for retrieveListMetaData
     *
     * Retrieve List of MetaData.
     *
     */
    public function testRetrieveListMetaData()
    {
    }

    /**
     * Test case for retrieveMetaData
     *
     * Retrieve a MetaData.
     *
     */
    public function testRetrieveMetaData()
    {
    }

    /**
     * Test case for setMetaData
     *
     * Set (create or update) a MetaData record.
     *
     */
    public function testSetMetaData()
    {
    }

    /**
     * Test case for updateMetaData
     *
     * Update a specific MetaData object.
     *
     */
    public function testUpdateMetaData()
    {
    }
}
