<?php
/**
 * QuestionnaireApiTest
 * PHP version 5
 *
 * @category Class
 * @package  BumbalClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bumbal Client Api
 *
 * Bumbal API documentation
 *
 * OpenAPI spec version: 2.0
 * Contact: gerb@bumbal.eu
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace BumbalClient;

use \BumbalClient\Configuration;
use \BumbalClient\ApiClient;
use \BumbalClient\ApiException;
use \BumbalClient\ObjectSerializer;

/**
 * QuestionnaireApiTest Class Doc Comment
 *
 * @category Class
 * @package  BumbalClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class QuestionnaireApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for changeLanguage
     *
     * change language of a Questionnaire.
     *
     */
    public function testChangeLanguage()
    {
    }

    /**
     * Test case for deleteQuestionnaire
     *
     * Delete an Questionnaire entry.
     *
     */
    public function testDeleteQuestionnaire()
    {
    }

    /**
     * Test case for getNextQuestion
     *
     * getNextQuestion of an Questionnaire.
     *
     */
    public function testGetNextQuestion()
    {
    }

    /**
     * Test case for getPreviousQuestion
     *
     * getPreviousQuestion of an Questionnaire.
     *
     */
    public function testGetPreviousQuestion()
    {
    }

    /**
     * Test case for retrieveListQuestionnaire
     *
     * Retrieve List of Questionnaire.
     *
     */
    public function testRetrieveListQuestionnaire()
    {
    }

    /**
     * Test case for retrieveQuestionnaire
     *
     * Retrieve a Questionnaire.
     *
     */
    public function testRetrieveQuestionnaire()
    {
    }
}
