<?php
/**
 * QuestionnairetemplatequestionApiTest
 * PHP version 5
 *
 * @category Class
 * @package  BumbalClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bumbal Client Api
 *
 * Bumbal API documentation
 *
 * OpenAPI spec version: 2.0
 * Contact: gerb@bumbal.eu
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace BumbalClient;

use \BumbalClient\Configuration;
use \BumbalClient\ApiClient;
use \BumbalClient\ApiException;
use \BumbalClient\ObjectSerializer;

/**
 * QuestionnairetemplatequestionApiTest Class Doc Comment
 *
 * @category Class
 * @package  BumbalClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class QuestionnairetemplatequestionApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createQuestionnaireTemplateQuestion
     *
     * Add a new QuestionnaireTemplateQuestion.
     *
     */
    public function testCreateQuestionnaireTemplateQuestion()
    {
    }

    /**
     * Test case for deleteQuestionnaireTemplateQuestion
     *
     * Delete an QuestionnaireTemplateQuestion entry.
     *
     */
    public function testDeleteQuestionnaireTemplateQuestion()
    {
    }

    /**
     * Test case for retrieveListQuestionnaireTemplateQuestion
     *
     * Retrieve List of QuestionnaireTemplateQuestion.
     *
     */
    public function testRetrieveListQuestionnaireTemplateQuestion()
    {
    }

    /**
     * Test case for retrieveQuestionnaireTemplateQuestion
     *
     * Retrieve a QuestionnaireTemplateQuestion.
     *
     */
    public function testRetrieveQuestionnaireTemplateQuestion()
    {
    }

    /**
     * Test case for setQuestionnaireTemplateQuestion
     *
     * Set (create or update) a QuestionnaireTemplateQuestion.
     *
     */
    public function testSetQuestionnaireTemplateQuestion()
    {
    }

    /**
     * Test case for updateQuestionnaireTemplateQuestion
     *
     * Update a specific QuestionnaireTemplateQuestion object.
     *
     */
    public function testUpdateQuestionnaireTemplateQuestion()
    {
    }
}
