<?php
/**
 * QuestionnairetemplateApiTest
 * PHP version 5
 *
 * @category Class
 * @package  BumbalClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bumbal Client Api
 *
 * Bumbal API documentation
 *
 * OpenAPI spec version: 2.0
 * Contact: gerb@bumbal.eu
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace BumbalClient;

use \BumbalClient\Configuration;
use \BumbalClient\ApiClient;
use \BumbalClient\ApiException;
use \BumbalClient\ObjectSerializer;

/**
 * QuestionnairetemplateApiTest Class Doc Comment
 *
 * @category Class
 * @package  BumbalClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class QuestionnairetemplateApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createQuestionnaireTemplate
     *
     * Add a new QuestionnaireTemplate.
     *
     */
    public function testCreateQuestionnaireTemplate()
    {
    }

    /**
     * Test case for deleteQuestionnaireTemplate
     *
     * Delete an QuestionnaireTemplate entry.
     *
     */
    public function testDeleteQuestionnaireTemplate()
    {
    }

    /**
     * Test case for retrieveListQuestionnaireTemplate
     *
     * Retrieve List of QuestionnaireTemplate.
     *
     */
    public function testRetrieveListQuestionnaireTemplate()
    {
    }

    /**
     * Test case for retrieveQuestionnaireTemplate
     *
     * Retrieve a QuestionnaireTemplate.
     *
     */
    public function testRetrieveQuestionnaireTemplate()
    {
    }

    /**
     * Test case for setQuestionnaireTemplate
     *
     * Set (create or update) a QuestionnaireTemplate.
     *
     */
    public function testSetQuestionnaireTemplate()
    {
    }

    /**
     * Test case for updateQuestionnaireTemplate
     *
     * Update a specific QuestionnaireTemplate object.
     *
     */
    public function testUpdateQuestionnaireTemplate()
    {
    }
}
