<?php
/**
 * QuestionnairetemplatequestionoptionApiTest
 * PHP version 5
 *
 * @category Class
 * @package  BumbalClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bumbal Client Api
 *
 * Bumbal API documentation
 *
 * OpenAPI spec version: 2.0
 * Contact: gerb@bumbal.eu
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace BumbalClient;

use \BumbalClient\Configuration;
use \BumbalClient\ApiClient;
use \BumbalClient\ApiException;
use \BumbalClient\ObjectSerializer;

/**
 * QuestionnairetemplatequestionoptionApiTest Class Doc Comment
 *
 * @category Class
 * @package  BumbalClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class QuestionnairetemplatequestionoptionApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createQuestionnaireTemplateQuestionOption
     *
     * Add a new QuestionnaireTemplateQuestionOption.
     *
     */
    public function testCreateQuestionnaireTemplateQuestionOption()
    {
    }

    /**
     * Test case for deleteQuestionnaireTemplateQuestionOption
     *
     * Delete an QuestionnaireTemplateQuestionOption entry.
     *
     */
    public function testDeleteQuestionnaireTemplateQuestionOption()
    {
    }

    /**
     * Test case for getPossibleFollowUpQuestions
     *
     * get possible follow up questions.
     *
     */
    public function testGetPossibleFollowUpQuestions()
    {
    }

    /**
     * Test case for retrieveListQuestionnaireTemplateQuestionOption
     *
     * Retrieve List of QuestionnaireTemplateQuestionOption.
     *
     */
    public function testRetrieveListQuestionnaireTemplateQuestionOption()
    {
    }

    /**
     * Test case for retrieveQuestionnaireTemplateQuestionOption
     *
     * Retrieve a QuestionnaireTemplateQuestionOption.
     *
     */
    public function testRetrieveQuestionnaireTemplateQuestionOption()
    {
    }

    /**
     * Test case for setQuestionnaireTemplateQuestionOption
     *
     * Set (create or update) a QuestionnaireTemplateQuestionOption.
     *
     */
    public function testSetQuestionnaireTemplateQuestionOption()
    {
    }

    /**
     * Test case for updateQuestionnaireTemplateQuestionOption
     *
     * Update a specific QuestionnaireTemplateQuestionOption object.
     *
     */
    public function testUpdateQuestionnaireTemplateQuestionOption()
    {
    }
}
