<?php
/**
 * RouteApiTest
 * PHP version 5
 *
 * @category Class
 * @package  BumbalClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bumbal Client Api
 *
 * Bumbal API documentation
 *
 * OpenAPI spec version: 2.0
 * Contact: gerb@bumbal.eu
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace BumbalClient;

use \BumbalClient\Configuration;
use \BumbalClient\ApiClient;
use \BumbalClient\ApiException;
use \BumbalClient\ObjectSerializer;

/**
 * RouteApiTest Class Doc Comment
 *
 * @category Class
 * @package  BumbalClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class RouteApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createRoute
     *
     * Add a new Route.
     *
     */
    public function testCreateRoute()
    {
    }

    /**
     * Test case for deleteRoute
     *
     * Delete an Route.
     *
     */
    public function testDeleteRoute()
    {
    }

    /**
     * Test case for getExecutableActivities
     *
     * Returns all activities in this route which hav enot been executed yet..
     *
     */
    public function testGetExecutableActivities()
    {
    }

    /**
     * Test case for retrieveListRoute
     *
     * Retrieve List of Routes.
     *
     */
    public function testRetrieveListRoute()
    {
    }

    /**
     * Test case for retrieveRoute
     *
     * Retrieve a Route.
     *
     */
    public function testRetrieveRoute()
    {
    }

    /**
     * Test case for routeStoreGeoLocations
     *
     * Store tracked Geo Locations in bulk.
     *
     */
    public function testRouteStoreGeoLocations()
    {
    }

    /**
     * Test case for setRoute
     *
     * Set (create or update) an Route.
     *
     */
    public function testSetRoute()
    {
    }

    /**
     * Test case for updateRoute
     *
     * Update a Route.
     *
     */
    public function testUpdateRoute()
    {
    }
}
