<?php
/**
 * TagtypeApiTest
 * PHP version 5
 *
 * @category Class
 * @package  BumbalClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bumbal Client Api
 *
 * Bumbal API documentation
 *
 * OpenAPI spec version: 2.0
 * Contact: gerb@bumbal.eu
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace BumbalClient;

use \BumbalClient\Configuration;
use \BumbalClient\ApiClient;
use \BumbalClient\ApiException;
use \BumbalClient\ObjectSerializer;

/**
 * TagtypeApiTest Class Doc Comment
 *
 * @category Class
 * @package  BumbalClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TagtypeApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createTagType
     *
     * Add a new Tag type.
     *
     */
    public function testCreateTagType()
    {
    }

    /**
     * Test case for deleteTagType
     *
     * Delete a Tag type.
     *
     */
    public function testDeleteTagType()
    {
    }

    /**
     * Test case for retrieveListTagType
     *
     * Retrieve List of Tag types.
     *
     */
    public function testRetrieveListTagType()
    {
    }

    /**
     * Test case for retrieveTagType
     *
     * Retrieve a Tag type.
     *
     */
    public function testRetrieveTagType()
    {
    }

    /**
     * Test case for setTagType
     *
     * Set (create or update) Tag type.
     *
     */
    public function testSetTagType()
    {
    }

    /**
     * Test case for updateTagType
     *
     * Update a Tag type.
     *
     */
    public function testUpdateTagType()
    {
    }
}
