<?php
/**
 * VehicletypeApiTest
 * PHP version 5
 *
 * @category Class
 * @package  BumbalClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Bumbal Client Api
 *
 * Bumbal API documentation
 *
 * OpenAPI spec version: 2.0
 * Contact: gerb@bumbal.eu
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace BumbalClient;

use \BumbalClient\Configuration;
use \BumbalClient\ApiClient;
use \BumbalClient\ApiException;
use \BumbalClient\ObjectSerializer;

/**
 * VehicletypeApiTest Class Doc Comment
 *
 * @category Class
 * @package  BumbalClient
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class VehicletypeApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createVehicleType
     *
     * Add a new VehicleType.
     *
     */
    public function testCreateVehicleType()
    {
    }

    /**
     * Test case for deleteVehicleType
     *
     * Delete a VehicleType entry.
     *
     */
    public function testDeleteVehicleType()
    {
    }

    /**
     * Test case for retrieveListVehicleType
     *
     * Retrieve List of VehicleTypes.
     *
     */
    public function testRetrieveListVehicleType()
    {
    }

    /**
     * Test case for retrieveVehicleType
     *
     * Retrieve a VehicleType.
     *
     */
    public function testRetrieveVehicleType()
    {
    }

    /**
     * Test case for updateVehicleType
     *
     * Update a specific VehicleType object.
     *
     */
    public function testUpdateVehicleType()
    {
    }
}
